### ISSUE TITLE
Použít ansible.builtin.package

### ISSUE THREAD

**Issue by xzavrel** [valouseko/ansible_data#1]
https://github.com/valouseko/ansible_data/blob/911af63b080e3af1409b1e489573edc2a51a0ca5/install_htop_nmap.yml#L18C5-L18C38

Podívej se na https://docs.ansible.com/ansible/latest/collections/ansible/builtin/package_module.html a zhodnoť, proč je to lepší použít, proti řešení, které jsi použil ty. Tam kde to půjde, to uprav.

**Comment by valouseko** [comment]
![image](https://github.com/user-attachments/assets/f90e3fe0-ef8f-42ae-b1b2-51d819cf5817)

**Comment by valouseko** [comment]
https://github.com/valouseko/ansible_data/blob/e9991d60d6cb85f05be8f4cb0775ea9a352a6adb/install_htop_nmap.yml

takhle to myslíš?

**Comment by xzavrel** [comment]
Když máš hotovo, označ to issue, jako hotové.
