### ISSUE TITLE
Udělat standardizovanou strukturu

### ISSUE THREAD

**Issue by xzavrel** [valouseko/ansible_data#2]
- [x] jednotlivým serverům nastav proměnnou `domain_name`, kterou nastavíš pomocí https://docs.ansible.com/ansible/latest/collections/ansible/builtin/hostname_module.html  -- proměnnou definuj v inventory.yaml
- [x] #5
- [x] při spuštění vypiš `ansible_distribution` a `ansible_distribution_major_version`

files
group_vars
host_vars
inventory
inventory/hosts.yaml
playbooks
roles
templates
main.yml

**Comment by valouseko** [comment]
omylem jsem smazal to dát ty servery do skupiny

**Comment by valouseko** [comment]
![image](https://github.com/user-attachments/assets/9e8c70ae-4999-4566-9d3a-6bff3ea0c0a9)
Vypisuje to ty distribuce
- udělal jsem na to samostatnou playbook, protože nevím jak je to myšleno "při spuštění..."

**Comment by xzavrel** [comment]
Vytvoř proměnnou `domain_name`, jejíž hodnota se použije pro nastavení hostname toho serveru v rámci toho `hostname_module`

**Comment by valouseko** [comment]
https://github.com/valouseko/ansible_data/blob/dd421b04acf48d5e7c9a677378ed1972a0db5ea2/set_a_hostname.yml

https://github.com/valouseko/ansible_data/blob/dd421b04acf48d5e7c9a677378ed1972a0db5ea2/inventory

**Comment by valouseko** [comment]
https://github.com/valouseko/ansible_data/blob/5c3b56cf15f6a2dc266b4e57daff07837caff180/debug_play.yml

A tady je to se rozbrazením distribuce a verze.
