### ISSUE TITLE
Pomocí Ansible vytvoř soubor s heslem

### ISSUE THREAD

**Issue by xzavrel** [valouseko/ansible_data#4]
Pomocí Ansible vytvoř v domovské složce uživatele soubor s heslem. Heslo bude uložené v Ansible zašifrované s využitím Ansible Vault. Každý server bude mít svoje heslo = svůj obsah souboru. Hodnotu nastavuj v host_vars/jmeno_serveru.yaml - viz https://github.com/valouseko/ansible_data/issues/2

Hint, jak vypadá heslo zašifrované pomocí Ansible Vault
```
pass: !vault |
                          $ANSIBLE_VAULT;1.1;AES256
                          30306265626562623363373039623365636261336433313465383238343664336331306237623330
                          3262666635616130613733306563663433663364326261300a333632623161636135633065386364
                          65346265643934613664336635633961663661616362323837383530303831663439666539393662
                          3065303830363938360a633664616263613138326539303264616163613862356565653362373238
                          6237
```

hint jak vytvořit soubor
```
  - name: Creating a file with content
    copy:
      dest: "/your path"
      content: |
        line 01
        line 02
```

**Comment by valouseko** [comment]
https://github.com/valouseko/ansible_data/blob/8225a08d9c800fd46eb6c3793bfd016834bcc787/copy_pass_file.yml

https://github.com/valouseko/ansible_data/tree/8225a08d9c800fd46eb6c3793bfd016834bcc787/host_vars

**Comment by xzavrel** [comment]
[heslo=pass: !vault |](https://github.com/valouseko/ansible_data/blob/8225a08d9c800fd46eb6c3793bfd016834bcc787/host_vars/server-debian.yml#L1)

tohle je asi nějak špatně

**Comment by valouseko** [comment]
Ajo, to je jenom chyba, něco jsem zkoušel a pak už to zapomněl opravit zpět, u ostatních je to v pořádku
