### ISSUE TITLE
Nainstalovat Javu 8 a Javu 11 

### ISSUE THREAD

**Issue by xzavrel** [valouseko/ansible_data#6]
- [x] Přidat si roli https://github.com/gantsign/ansible-role-java
- [x] Pomocí této role nainstalovat Javu 8
- [x] Pomocí této role nainstalovat Javu 17 a nastavit ji jako výchozí (obě verze budou instalované současně)

**Comment by valouseko** [comment]
https://github.com/valouseko/ansible_data/blob/cb68bd9e96d869feefae8cc256a9edf47574297a/install_java.yml

(Jen jsem se překlikl v názvu commitu)

**Comment by xzavrel** [comment]
Ještě si prosím v playbooku vypiš kam se ta java nainstalovala

**Comment by valouseko** [comment]
https://github.com/valouseko/ansible_data/blob/6327f7bf5fd804ad2c3dd6a3e93fcf44f3b3a9d3/install_java.yml

**Comment by xzavrel** [comment]
Tak ještě poprosím o Ansible řešení a vypsat pro obě nainstalované verze Javy. 
V Ansible se používají fakty a jedním z nich je i home. Pro každou verzi si musíš nastavit java_fact_group_name, aby se ti nepletly mezi sebou.

V té roli je to popsané https://github.com/gantsign/ansible-role-java?tab=readme-ov-file#role-facts


```
# Name of the group of Ansible facts relating this Java installation.
#
# Override if you want use this role more than once to install multiple versions
# of Java.
#
# e.g. java_fact_group_name: java_8
# would change the Java home fact to:
# ansible_local.java_8.general.home
java_fact_group_name: java
```

**Comment by valouseko** [comment]
https://github.com/valouseko/ansible_data/blob/2f5880d89ac72d482d5f9c13397c2f5469c1a952/install_java.yml
